apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: custom-config
spec:
  # namespace: chainsaw
  timeouts:
    apply: 300s
    assert: 300s
    cleanup: 120s
    delete: 120s
    error: 180s
    exec: 300s
  # skipDelete: false
  failFast: true
  forceTerminationGracePeriod: 10s
  parallel: 1
