apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: custom-config
spec:
  namespace: kubedatastack
  timeouts:
    apply: 3000s
    assert: 3000s
    cleanup: 120s
    delete: 120s
    error: 240s
    exec: 200s
  skipDelete: false
  failFast: true
  forceTerminationGracePeriod: 10s
